load ../../../tool/param.maude

load ../../../tool/state.maude

load ../../../model/onethirdrule-vu-narrow.maude

{fold} vu-narrow {filter,delay} [1] in ONETHIRDRULE-VU-NARROW-ANALYSIS :
{s, OS, INITIAL} ||| (noDupl(OS) and noDupl(getOids(INITIAL)) and 
            sameRound(getRounds(INITIAL)) and twoVoteMapEntry(INITIAL))
=>* 
{s, OS,
< O : Node | decision : 0, ATTS >
< O' : Node | decision : s, ATTS' >
CF} ||| PHI .
