load ../../../tool/param.maude

load ../../../tool/state.maude

load ../../../model/onethirdrule-vu-narrow.maude

{fold} vu-narrow {filter,delay} [1] in ONETHIRDRULE-VU-NARROW-ANALYSIS :
{TH, OS, INITIAL} || (noDupl(OS) and noDupl(getOids(INITIAL)) and 
            sameRound(getRounds(INITIAL)) and valid1/2(numObjs(INITIAL), TH))
=>* 
{TH, OS,
< O : Node | decision : true, ATTS >
< O' : Node | decision : false, ATTS' >
CF} || PHI .
