load ../../../tool/param.maude

load ../../../tool/state.maude

load ../../../model/onethirdrule-vu-narrow.maude

{fold} vu-narrow {filter,delay} [1] in ONETHIRDRULE-NML-VU-NARROW-ANALYSIS :
{TH, s ; s s, OS, INITIAL} || (noDupl(OS) and noDupl(getOids(INITIAL)) and 
            sameRound(getRounds(INITIAL)) and valid1/2(numObjs(INITIAL), TH)
            and checkVoteMaps((s ; s s), getVoteMaps(INITIAL)))
=>* 
{TH, s ; s s, OS,
< O : Node | decision : s, ATTS >
< O' : Node | decision : s s, ATTS' >
CF} || PHI .
