load ../tool/param.maude
load ../tool/state.maude
load ../tool/tool.maude
load ../model/lamport-bakery.maude

mod BAKERY-VU-NARROW-ANALYSIS is
    protecting BAKERY .
    protecting BAKERY-CONST .
    protecting HNR-TOP .
    including STATE . 

    subsort Global < State .

    vars O O' : Oid . 
    var OS : OidSet .
    var CF : Configuration .
    var PHI : Bool .
    vars N M N' M' : Natural .
    var INIT : InitConfiguration .

endm 

{fold} vu-narrow {filter,delay} [1] in BAKERY-VU-NARROW-ANALYSIS :
{0, 0, INIT} ||| noDupl(getOids(INIT))
=>* 
{N', M',
< O : Node | status : (crit(s s s s)) >
< O' : Node | status : (crit(s s s s)) >
CF} ||| PHI .
