
load ../tool/param.maude
load aux-functions/onethirdrule-index.maude
load aux-functions/onethirdrule-scoring-functions.maude

load ../tool/state.maude
load ../tool/tool.maude

load ../model/onethirdrule.maude


mod MAIN is
    protecting ONETHIRDRULE-ANALYSIS .
    protecting ONETHIRDRULE-INDEX .
    protecting ONETHIRDRULE-SCORE-1 .
    protecting HEURISTIC-NARROWING-DRIVER .

    var N : Natural .
    vars O O' : Oid .
    var OS : OidSet .
    var INITIAL : InitConfiguration .
    var IOBJ1 IOBJ2 IOBJ3 : InitObject .
    vars ATTS ATTS' : U124S .
    var CF : Configuration .

endm

red heuristic-narrow {filter delay} in 'ONETHIRDRULE-ANALYSIS : 
      {s, OS, IOBJ1 IOBJ2 IOBJ3} 
  =>* {N, OS, < O  : Node | decision : true,  ATTS  >
              < O' : Node | decision : false, ATTS' > CF}
  such that noDupl(OS) and noDupl(getOids(IOBJ1 IOBJ2 IOBJ3)) and 
            sameRound(getRounds(IOBJ1 IOBJ2 IOBJ3)) .


red heuristic-narrow {filter delay} in 'ONETHIRDRULE-ANALYSIS : 
      {s, OS, INITIAL} 
  =>* {N, OS, < O  : Node | decision : true,  ATTS  >
              < O' : Node | decision : false, ATTS' > CF}
  such that noDupl(OS) and noDupl(getOids(INITIAL)) and 
            sameRound(getRounds(INITIAL)) .


red heuristic-narrow {filter delay} in 'ONETHIRDRULE-ANALYSIS : 
      {N, OS, IOBJ1 IOBJ2 IOBJ3} 
  =>* {N, OS, < O  : Node | decision : true,  ATTS  >
              < O' : Node | decision : false, ATTS' > CF}
  such that noDupl(OS) and noDupl(getOids(IOBJ1 IOBJ2 IOBJ3)) and 
            sameRound(getRounds(IOBJ1 IOBJ2 IOBJ3)) and 
            valid1/2(numObjs(IOBJ1 IOBJ2 IOBJ3), N) .


red heuristic-narrow {filter delay} in 'ONETHIRDRULE-ANALYSIS : 
      {N, OS, INITIAL} 
  =>* {N, OS, < O  : Node | decision : true,  ATTS  >
              < O' : Node | decision : false, ATTS' > CF}
  such that noDupl(OS) and noDupl(getOids(INITIAL)) and 
            sameRound(getRounds(INITIAL)) and valid1/2(numObjs(INITIAL), N) .
