load ../../heuristic-search/main.maude
load ../model-extensions/onethirdrule-index.maude
load ../model-extensions/onethirdrule-scoring-functions.maude
load ../model-extensions/onethirdrule-term-transformer.maude


mod ONETHIRDRULE-TEST-SCORE1 is
    protecting ONETHIRDRULE-INDEX .
    protecting ONETHIRDRULE-TERM-TRANSFORMER .
    protecting ONETHIRDRULE-SCORE1 .
    protecting HEURISTIC-NARROWING .
endm

mod ONETHIRDRULE-TEST-SCORE2 is
    protecting ONETHIRDRULE-INDEX .
    protecting ONETHIRDRULE-TERM-TRANSFORMER .
    protecting ONETHIRDRULE-SCORE2 .
    protecting HEURISTIC-NARROWING .
endm

mod ONETHIRDRULE-TEST-SCORE3 is
    protecting ONETHIRDRULE-INDEX .
    protecting ONETHIRDRULE-TERM-TRANSFORMER .
    protecting ONETHIRDRULE-SCORE3 .
    protecting HEURISTIC-NARROWING .
endm

*** static + dynamic reduction
load ../../models/onethirdrule-static-dynamic.maude

red in ONETHIRDRULE-TEST-SCORE3 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-STATIC-DYNAMIC-FIXED-OBJS, false),
    '`{_`,_`,_`}['__['s.Natural,'s.Natural,'s.Natural],'_;_['O1:Oid,
    'O2:Oid,'O3:Oid],'__['<_:_|_>['O1:Oid,'Node.Cid,'_`,_['status`:_['`[_`,_`][
    'R:Natural,'init.InitialStep]],'value`:_['V1:Value],'decision`:_[
    'nil.InitialValue],'votes`:_['`[_`,_`,_`]['0.Zero,'0.Zero,'0.Zero]]]],
    '<_:_|_>['O2:Oid,'Node.Cid,'_`,_['status`:_['`[_`,_`]['R:Natural,
    'init.InitialStep]],'value`:_['V2:Value],'decision`:_['nil.InitialValue],
    'votes`:_['`[_`,_`,_`]['0.Zero,'0.Zero,'0.Zero]]]],'<_:_|_>['O3:Oid,
    'Node.Cid,'_`,_['status`:_['`[_`,_`]['R:Natural,'init.InitialStep]],
    'value`:_['V3:Value],'decision`:_['nil.InitialValue],'votes`:_['`[_`,_`,_`][
    '0.Zero,'0.Zero,'0.Zero]]]]]],
    '`{_`,_`,_`}['N:Natural,'OS:OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    'vote-by-existing ; 'receive,
    delay filter, unlimited) .

do clear memo .


red in ONETHIRDRULE-TEST-SCORE2 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-STATIC-DYNAMIC-FIXED-OBJS, false),
    '`{_`,_`,_`}['__['s.Natural,'s.Natural,'s.Natural],'_;_['O1:Oid,
    'O2:Oid,'O3:Oid],'__['<_:_|_>['O1:Oid,'Node.Cid,'_`,_['status`:_['`[_`,_`][
    'R:Natural,'init.InitialStep]],'value`:_['V1:Value],'decision`:_[
    'nil.InitialValue],'votes`:_['`[_`,_`,_`]['0.Zero,'0.Zero,'0.Zero]]]],
    '<_:_|_>['O2:Oid,'Node.Cid,'_`,_['status`:_['`[_`,_`]['R:Natural,
    'init.InitialStep]],'value`:_['V2:Value],'decision`:_['nil.InitialValue],
    'votes`:_['`[_`,_`,_`]['0.Zero,'0.Zero,'0.Zero]]]],'<_:_|_>['O3:Oid,
    'Node.Cid,'_`,_['status`:_['`[_`,_`]['R:Natural,'init.InitialStep]],
    'value`:_['V3:Value],'decision`:_['nil.InitialValue],'votes`:_['`[_`,_`,_`][
    '0.Zero,'0.Zero,'0.Zero]]]]]],
    '`{_`,_`,_`}['N:Natural,'OS:OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    'vote-by-existing ; 'receive,
    delay filter, unlimited) .

do clear memo .

red in ONETHIRDRULE-TEST-SCORE1 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-STATIC-DYNAMIC-FIXED-OBJS, false),
    '`{_`,_`,_`}['__['s.Natural,'s.Natural,'s.Natural],'_;_['O1:Oid,
    'O2:Oid,'O3:Oid],'__['<_:_|_>['O1:Oid,'Node.Cid,'_`,_['status`:_['`[_`,_`][
    'R:Natural,'init.InitialStep]],'value`:_['V1:Value],'decision`:_[
    'nil.InitialValue],'votes`:_['`[_`,_`,_`]['0.Zero,'0.Zero,'0.Zero]]]],
    '<_:_|_>['O2:Oid,'Node.Cid,'_`,_['status`:_['`[_`,_`]['R:Natural,
    'init.InitialStep]],'value`:_['V2:Value],'decision`:_['nil.InitialValue],
    'votes`:_['`[_`,_`,_`]['0.Zero,'0.Zero,'0.Zero]]]],'<_:_|_>['O3:Oid,
    'Node.Cid,'_`,_['status`:_['`[_`,_`]['R:Natural,'init.InitialStep]],
    'value`:_['V3:Value],'decision`:_['nil.InitialValue],'votes`:_['`[_`,_`,_`][
    '0.Zero,'0.Zero,'0.Zero]]]]]],
    '`{_`,_`,_`}['N:Natural,'OS:OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    'vote-by-existing ; 'receive,
    delay filter, unlimited) .

do clear memo .

*** static reduction
load ../../models/onethirdrule-static.maude

red in ONETHIRDRULE-TEST-SCORE3 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-STATIC-FIXED-OBJS, false),
    '`{_`,_`,_`}['__['s.Natural,'s.Natural,'s.Natural],'_;_['O1:Oid,
    'O2:Oid,'O3:Oid],'__['<_:_|_>['O1:Oid,'Node.Cid,'_`,_['status`:_['`[_`,_`][
    'R:Natural,'init.InitialStep]],'value`:_['V1:Value],'decision`:_[
    'nil.InitialValue],'votes`:_['`[_`,_`,_`]['0.Zero,'0.Zero,'0.Zero]]]],
    '<_:_|_>['O2:Oid,'Node.Cid,'_`,_['status`:_['`[_`,_`]['R:Natural,
    'init.InitialStep]],'value`:_['V2:Value],'decision`:_['nil.InitialValue],
    'votes`:_['`[_`,_`,_`]['0.Zero,'0.Zero,'0.Zero]]]],'<_:_|_>['O3:Oid,
    'Node.Cid,'_`,_['status`:_['`[_`,_`]['R:Natural,'init.InitialStep]],
    'value`:_['V3:Value],'decision`:_['nil.InitialValue],'votes`:_['`[_`,_`,_`][
    '0.Zero,'0.Zero,'0.Zero]]]]]],
    '`{_`,_`,_`}['N:Natural,'OS:OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    none,
    delay filter, unlimited) .

do clear memo .

red in ONETHIRDRULE-TEST-SCORE2 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-STATIC-FIXED-OBJS, false),
    '`{_`,_`,_`}['__['s.Natural,'s.Natural,'s.Natural],'_;_['O1:Oid,
    'O2:Oid,'O3:Oid],'__['<_:_|_>['O1:Oid,'Node.Cid,'_`,_['status`:_['`[_`,_`][
    'R:Natural,'init.InitialStep]],'value`:_['V1:Value],'decision`:_[
    'nil.InitialValue],'votes`:_['`[_`,_`,_`]['0.Zero,'0.Zero,'0.Zero]]]],
    '<_:_|_>['O2:Oid,'Node.Cid,'_`,_['status`:_['`[_`,_`]['R:Natural,
    'init.InitialStep]],'value`:_['V2:Value],'decision`:_['nil.InitialValue],
    'votes`:_['`[_`,_`,_`]['0.Zero,'0.Zero,'0.Zero]]]],'<_:_|_>['O3:Oid,
    'Node.Cid,'_`,_['status`:_['`[_`,_`]['R:Natural,'init.InitialStep]],
    'value`:_['V3:Value],'decision`:_['nil.InitialValue],'votes`:_['`[_`,_`,_`][
    '0.Zero,'0.Zero,'0.Zero]]]]]],
    '`{_`,_`,_`}['N:Natural,'OS:OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    none,
    delay filter, unlimited) .

do clear memo .

red in ONETHIRDRULE-TEST-SCORE1 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-STATIC-FIXED-OBJS, false),
    '`{_`,_`,_`}['__['s.Natural,'s.Natural,'s.Natural],'_;_['O1:Oid,
    'O2:Oid,'O3:Oid],'__['<_:_|_>['O1:Oid,'Node.Cid,'_`,_['status`:_['`[_`,_`][
    'R:Natural,'init.InitialStep]],'value`:_['V1:Value],'decision`:_[
    'nil.InitialValue],'votes`:_['`[_`,_`,_`]['0.Zero,'0.Zero,'0.Zero]]]],
    '<_:_|_>['O2:Oid,'Node.Cid,'_`,_['status`:_['`[_`,_`]['R:Natural,
    'init.InitialStep]],'value`:_['V2:Value],'decision`:_['nil.InitialValue],
    'votes`:_['`[_`,_`,_`]['0.Zero,'0.Zero,'0.Zero]]]],'<_:_|_>['O3:Oid,
    'Node.Cid,'_`,_['status`:_['`[_`,_`]['R:Natural,'init.InitialStep]],
    'value`:_['V3:Value],'decision`:_['nil.InitialValue],'votes`:_['`[_`,_`,_`][
    '0.Zero,'0.Zero,'0.Zero]]]]]],
    '`{_`,_`,_`}['N:Natural,'OS:OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    none,
    delay filter, unlimited) .

do clear memo .

*** no reduction
load ../../models/onethirdrule.maude

red in ONETHIRDRULE-TEST-SCORE3 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-FIXED-OBJS, false),
    '`{_`,_`,_`}['__['s.Natural,'s.Natural,'s.Natural],'_;_['O1:Oid,
    'O2:Oid,'O3:Oid],'__['<_:_|_>['O1:Oid,'Node.Cid,'_`,_['status`:_['`[_`,_`][
    'R:Natural,'init.InitialStep]],'value`:_['V1:Value],'decision`:_[
    'nil.InitialValue],'votes`:_['`[_`,_`,_`]['0.Zero,'0.Zero,'0.Zero]]]],
    '<_:_|_>['O2:Oid,'Node.Cid,'_`,_['status`:_['`[_`,_`]['R:Natural,
    'init.InitialStep]],'value`:_['V2:Value],'decision`:_['nil.InitialValue],
    'votes`:_['`[_`,_`,_`]['0.Zero,'0.Zero,'0.Zero]]]],'<_:_|_>['O3:Oid,
    'Node.Cid,'_`,_['status`:_['`[_`,_`]['R:Natural,'init.InitialStep]],
    'value`:_['V3:Value],'decision`:_['nil.InitialValue],'votes`:_['`[_`,_`,_`][
    '0.Zero,'0.Zero,'0.Zero]]]]]],
    '`{_`,_`,_`}['N:Natural,'OS:OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    none,
    delay filter, unlimited) .

do clear memo .

red in ONETHIRDRULE-TEST-SCORE2 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-FIXED-OBJS, false),
    '`{_`,_`,_`}['__['s.Natural,'s.Natural,'s.Natural],'_;_['O1:Oid,
    'O2:Oid,'O3:Oid],'__['<_:_|_>['O1:Oid,'Node.Cid,'_`,_['status`:_['`[_`,_`][
    'R:Natural,'init.InitialStep]],'value`:_['V1:Value],'decision`:_[
    'nil.InitialValue],'votes`:_['`[_`,_`,_`]['0.Zero,'0.Zero,'0.Zero]]]],
    '<_:_|_>['O2:Oid,'Node.Cid,'_`,_['status`:_['`[_`,_`]['R:Natural,
    'init.InitialStep]],'value`:_['V2:Value],'decision`:_['nil.InitialValue],
    'votes`:_['`[_`,_`,_`]['0.Zero,'0.Zero,'0.Zero]]]],'<_:_|_>['O3:Oid,
    'Node.Cid,'_`,_['status`:_['`[_`,_`]['R:Natural,'init.InitialStep]],
    'value`:_['V3:Value],'decision`:_['nil.InitialValue],'votes`:_['`[_`,_`,_`][
    '0.Zero,'0.Zero,'0.Zero]]]]]],
    '`{_`,_`,_`}['N:Natural,'OS:OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    none,
    delay filter, unlimited) .

do clear memo .

red in ONETHIRDRULE-TEST-SCORE1 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-FIXED-OBJS, false),
    '`{_`,_`,_`}['__['s.Natural,'s.Natural,'s.Natural],'_;_['O1:Oid,
    'O2:Oid,'O3:Oid],'__['<_:_|_>['O1:Oid,'Node.Cid,'_`,_['status`:_['`[_`,_`][
    'R:Natural,'init.InitialStep]],'value`:_['V1:Value],'decision`:_[
    'nil.InitialValue],'votes`:_['`[_`,_`,_`]['0.Zero,'0.Zero,'0.Zero]]]],
    '<_:_|_>['O2:Oid,'Node.Cid,'_`,_['status`:_['`[_`,_`]['R:Natural,
    'init.InitialStep]],'value`:_['V2:Value],'decision`:_['nil.InitialValue],
    'votes`:_['`[_`,_`,_`]['0.Zero,'0.Zero,'0.Zero]]]],'<_:_|_>['O3:Oid,
    'Node.Cid,'_`,_['status`:_['`[_`,_`]['R:Natural,'init.InitialStep]],
    'value`:_['V3:Value],'decision`:_['nil.InitialValue],'votes`:_['`[_`,_`,_`][
    '0.Zero,'0.Zero,'0.Zero]]]]]],
    '`{_`,_`,_`}['N:Natural,'OS:OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    none,
    delay filter, unlimited) .