load ../../heuristic-search/main.maude
load ../model-extensions/onethirdrule-index.maude
load ../model-extensions/onethirdrule-scoring-functions.maude
load ../model-extensions/onethirdrule-term-transformer.maude


mod ONETHIRDRULE-TEST-SCORE1 is
    protecting ONETHIRDRULE-INDEX .
    protecting ONETHIRDRULE-TERM-TRANSFORMER .
    protecting ONETHIRDRULE-SCORE1 .
    protecting HEURISTIC-NARROWING .
endm

mod ONETHIRDRULE-TEST-SCORE2 is
    protecting ONETHIRDRULE-INDEX .
    protecting ONETHIRDRULE-TERM-TRANSFORMER .
    protecting ONETHIRDRULE-SCORE2 .
    protecting HEURISTIC-NARROWING .
endm

mod ONETHIRDRULE-TEST-SCORE3 is
    protecting ONETHIRDRULE-INDEX .
    protecting ONETHIRDRULE-TERM-TRANSFORMER .
    protecting ONETHIRDRULE-SCORE3 .
    protecting HEURISTIC-NARROWING .
endm

*** static + dynamic reduction
load ../../models/onethirdrule-static-dynamic.maude

red in ONETHIRDRULE-TEST-SCORE3 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-STATIC-DYNAMIC-HALF, false),
    '`{_`,_`,_`}['N:Natural, 'OS:OidSet, 'INITIAL:InitObjectSet],
    '`{_`,_`,_`}['N:Natural,'OS:OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    'vote-by-existing ; 'receive,
    delay filter, unlimited) .

do clear memo .

red in ONETHIRDRULE-TEST-SCORE2 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-STATIC-DYNAMIC-HALF, false),
    '`{_`,_`,_`}['N:Natural, 'OS:OidSet, 'INITIAL:InitObjectSet],
    '`{_`,_`,_`}['N:Natural,'OS:OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    'vote-by-existing ; 'receive,
    delay filter, unlimited) .

do clear memo .

***(
red in ONETHIRDRULE-TEST-SCORE1 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-STATIC-DYNAMIC-HALF, false),
    '`{_`,_`,_`}['N:Natural, 'OS:OidSet, 'INITIAL:InitObjectSet],
    '`{_`,_`,_`}['N:Natural,'OS:OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    'vote-by-existing ; 'receive,
    delay filter, unlimited) .

do clear memo .
)

*** static reduction

load ../../models/onethirdrule-static.maude

red in ONETHIRDRULE-TEST-SCORE3 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-STATIC-HALF, false),
    '`{_`,_`,_`}['N:Natural, 'OS:OidSet, 'INITIAL:InitObjectSet],
    '`{_`,_`,_`}['N:Natural,'OS:OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    none, delay filter, unlimited) .

do clear memo .

red in ONETHIRDRULE-TEST-SCORE2 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-STATIC-HALF, false),
    '`{_`,_`,_`}['N:Natural, 'OS:OidSet, 'INITIAL:InitObjectSet],
    '`{_`,_`,_`}['N:Natural,'OS:OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    none, delay filter, unlimited) .

do clear memo .

***(
red in ONETHIRDRULE-TEST-SCORE1 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-STATIC-HALF, false),
    '`{_`,_`,_`}['N:Natural, 'OS:OidSet, 'INITIAL:InitObjectSet],
    '`{_`,_`,_`}['N:Natural,'OS:OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    none, delay filter, unlimited) .

do clear memo .
)

*** no reduction

load ../../models/onethirdrule.maude

red in ONETHIRDRULE-TEST-SCORE3 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-HALF, false),
    '`{_`,_`,_`}['N:Natural, 'OS:OidSet, 'INITIAL:InitObjectSet],
    '`{_`,_`,_`}['N:Natural,'OS:OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    none, delay filter, unlimited) .

do clear memo .

red in ONETHIRDRULE-TEST-SCORE2 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-HALF, false),
    '`{_`,_`,_`}['N:Natural, 'OS:OidSet, 'INITIAL:InitObjectSet],
    '`{_`,_`,_`}['N:Natural,'OS:OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    none, delay filter, unlimited) .

do clear memo .

***(
red in ONETHIRDRULE-TEST-SCORE1 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-HALF, false),
    '`{_`,_`,_`}['N:Natural, 'OS:OidSet, 'INITIAL:InitObjectSet],
    '`{_`,_`,_`}['N:Natural,'OS:OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    none, delay filter, unlimited) .
)