
load ../../tool/param.maude
load ../aux-functions/onethirdrule-index.maude
load ../aux-functions/onethirdrule-scoring-functions.maude

load ../../tool/state.maude
load ../../tool/tool.maude

load ../../model/onethirdrule.maude

mod TEST-BASE is 
    protecting ONETHIRDRULE-ANALYSIS .
    protecting ONETHIRDRULE-INDEX .
    protecting HEURISTIC-NARROWING-DRIVER .

    vars TH R : Natural .
    vars O1 O2 O3 : Oid .
    vars V1 V2 V3 : Value .
    var VS : ValueSet .

    op init3 : Natural ValueSet Oid Oid Oid Natural Value Value Value -> Global .
    eq init3(TH, VS, O1, O2, O3, R, V1, V2, V3)
    = {TH, VS, O1 ; O2 ; O3,
        < O1 : Node | status : [R, init], value : V1, decision : nil, votes : [initVotes(VS), 0] >
        < O2 : Node | status : [R, init], value : V2, decision : nil, votes : [initVotes(VS), 0] >
        < O3 : Node | status : [R, init], value : V3, decision : nil, votes : [initVotes(VS), 0] >} .
endm

mod TEST-BFS is
    protecting TEST-BASE .
    protecting ONETHIRDRULE-SCORE-BFS .

    vars TH R : Natural .
    vars O O' O1 O2 O3 : Oid .
    vars V1 V2 V3 : Value .
    var OS : OidSet .
    var INITIAL : InitConfiguration .
    vars ATTS ATTS' : U124S .
    var CF : Configuration .
endm

mod TEST-G is
    protecting TEST-BASE .
    protecting ONETHIRDRULE-SCORE-G .

    vars TH R : Natural .
    vars O O' O1 O2 O3 : Oid .
    vars V1 V2 V3 : Value .
    var OS : OidSet .
    var INITIAL : InitConfiguration .
    vars ATTS ATTS' : U124S .
    var CF : Configuration .
endm

mod TEST-1 is
    protecting TEST-BASE .
    protecting ONETHIRDRULE-SCORE-1 .

    vars TH R : Natural .
    vars O O' O1 O2 O3 : Oid .
    vars V1 V2 V3 : Value .
    var OS : OidSet .
    var INITIAL : InitConfiguration .
    vars ATTS ATTS' : U124S .
    var CF : Configuration .
endm

mod TEST-2 is
    protecting TEST-BASE .
    protecting ONETHIRDRULE-SCORE-2 .

    vars TH R : Natural .
    vars O O' O1 O2 O3 : Oid .
    vars V1 V2 V3 : Value .
    var OS : OidSet .
    var INITIAL : InitConfiguration .
    vars ATTS ATTS' : U124S .
    var CF : Configuration .
endm

mod TEST-3 is
    protecting TEST-BASE .
    protecting ONETHIRDRULE-SCORE-3 .

    vars TH R : Natural .
    vars O O' O1 O2 O3 : Oid .
    vars V1 V2 V3 : Value .
    var OS : OidSet .
    var INITIAL : InitConfiguration .
    vars ATTS ATTS' : U124S .
    var CF : Configuration .
endm