
load ../heuristic-search/param.maude
load aux-functions/onethirdrule-index.maude
load aux-functions/onethirdrule-scoring-functions.maude
load aux-functions/onethirdrule-term-transformer.maude


load ../heuristic-search/tool.maude

mod DRIVER4 is
    protecting ONETHIRDRULE-INDEX .
    protecting ONETHIRDRULE-TERM-TRANSFORMER .
    protecting ONETHIRDRULE-SCORE4 .
    protecting HEURISTIC-NARROWING .
endm


load ../models/onethirdrule.maude


red in DRIVER4 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-WITH-INV-HALF, false),
    '`{_`,_`,_`}['N:Natural, 'OS:OidSet, 'INITIAL:InitConfiguration],
    '`{_`,_`,_`}['N:Natural,'OS:OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    delay filter) .
