load ../heuristic-search/main.maude
load ./model-extensions/onethirdrule-index.maude
load ./model-extensions/onethirdrule-scoring-functions.maude
load ./model-extensions/onethirdrule-invariant.maude


mod ONETHIRDRULE-TEST-SCORE1 is
    protecting ONETHIRDRULE-INDEX .
    protecting ONETHIRDRULE-SCORE1 .
    protecting HEURISTIC-NARROWING .
endm



set print attribute on .

red in ONETHIRDRULE-TEST-SCORE1 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-INVARIANT-HALF, false),
    '`{_`,_`,_`}['N:Nat, 'OIDS:OidSet, 'INITIAL:InitialObjectSet],
    '`{_`,_`,_`}['N':Nat,'OIDS':OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.FvpBool]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.InitialFvpBool]]]]],
    (['vote-true, any] ; 
    ['vote-false, any] ; 
    ['receive-true-vote, any] ; 
    ['receive-false-vote, any]),
    delay filter) .
