load ../heuristic-search/heuristic-search.maude
load ../heuristic-search/rule-instance.maude
load ../models/onethirdrule.maude
load ./scoring-functions.maude

mod ONETHIRDRULE-INITIALCOND is
    protecting ONETHIRDRULE .
    including HEURISTIC-SEARCH .

    var N : Nat .
    var CONF : Configuration .
    var M : Msg .
    vars O O' : Oid .
    var C : Cid .
    vars OIDS NEIGHBORS : OidSet .
    var Z : Zero .

    eq inv(SK:[State]) = true .
    eq initialCond({N, OIDS, CONF}) 
    = noDuplicate(OIDS) 
    and noDuplicate(getOids(CONF)) 
    and isThresholdValid(getOids(CONF), N) .

    op getOids : Configuration -> OidSet [memo] .
    eq getOids(< O : C | ATTS:U1234S > CONF) = O ; getOids(CONF) .
    eq getOids(M CONF) =  getOids(CONF) .
    eq getOids(none) =  none .

    op noDuplicate : OidSet -> Bool [memo] .
    eq noDuplicate(O ; O ; OIDS) = false .

    op isThresholdValid : OidSet Nat -> Bool [memo] .
    eq isThresholdValid((O ; O' ; OIDS), s N) = isThresholdValid(OIDS, N) .
    eq isThresholdValid(OIDS, Z) = false .
endm


mod ONETHIRDRULE-TEST-1 is
    including ONETHIRDRULE-INITIALCOND .
    protecting SCORE1 * (sort Nat to Nat', sort Zero to Zero') .

    vars O O' : Oid .
    vars N N' : Nat .
    vars OIDS OIDS' : OidSet .
    var INITIAL : InitialObjectSet .
    var CONF : Configuration .
endm

mod ONETHIRDRULE-TEST-2 is
    including ONETHIRDRULE-INITIALCOND .
    protecting SCORE2 * (sort Nat to Nat', sort Zero to Zero') .

    vars O O' : Oid .
    vars N N' : Nat .
    vars OIDS OIDS' : OidSet .
    var INITIAL : InitialObjectSet .
    var CONF : Configuration .
endm

mod ONETHIRDRULE-TEST-3 is
    including ONETHIRDRULE-INITIALCOND .
    protecting SCORE3 * (sort Nat to Nat', sort Zero to Zero') .

    vars O O' : Oid .
    vars N N' : Nat .
    vars OIDS OIDS' : OidSet .
    var INITIAL : InitialObjectSet .
    var CONF : Configuration .
endm

do clear memo .

red in ONETHIRDRULE-TEST-3 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-INITIALCOND, false),
    upTerm({N, OIDS, INITIAL}),
    upTerm({N', OIDS',
    < O : Node | decision : true, ATTS:U124S >
    < O' : Node | decision : false, ATTS':U124S >
    CONF}),
    none,
    delay filter) .

do clear memo .

red in ONETHIRDRULE-TEST-2 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-INITIALCOND, false),
    upTerm({N, OIDS, INITIAL}),
    upTerm({N', OIDS',
    < O : Node | decision : true, ATTS:U124S >
    < O' : Node | decision : false, ATTS':U124S >
    CONF}),
    none,
    delay filter) .

do clear memo .

red in ONETHIRDRULE-TEST-1 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-INITIALCOND, false),
    upTerm({N, OIDS, INITIAL}),
    upTerm({N', OIDS',
    < O : Node | decision : true, ATTS:U124S >
    < O' : Node | decision : false, ATTS':U124S >
    CONF}),
    none,
    delay filter) .