load ../heuristic-search/main.maude
load ./model-extensions/onethirdrule-index.maude
load ./model-extensions/onethirdrule-scoring-functions.maude
load ./model-extensions/onethirdrule-vu-narrow-invariant.maude


mod ONETHIRDRULE-TEST-SCORE1 is
    protecting ONETHIRDRULE-VU-NARROW-INDEX .
    protecting ONETHIRDRULE-VU-NARROW-SCORE1 .
    protecting HEURISTIC-NARROWING .
endm

mod ONETHIRDRULE-TEST-SCORE2 is
    protecting ONETHIRDRULE-VU-NARROW-INDEX .
    protecting ONETHIRDRULE-VU-NARROW-SCORE2 .
    protecting HEURISTIC-NARROWING .
endm

mod ONETHIRDRULE-TEST-SCORE3 is
    protecting ONETHIRDRULE-VU-NARROW-INDEX .
    protecting ONETHIRDRULE-VU-NARROW-SCORE3 .
    protecting HEURISTIC-NARROWING .
endm


red in ONETHIRDRULE-TEST-SCORE3 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-VU-NARROW-WITH-INV, false),
    'ready['`{_`,_`,_`}['s.Nat, 'OIDS:OidSet, 'INITIAL:InitialObjectSet]],
    'ready['`{_`,_`,_`}['s.Nat,'OIDS':OidSet,'__['CONF:Configuration,
    '<_:_|_>['O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Bool']]]]]],
    (['vote-true, any] ; 
    ['vote-false, any] ; 
    ['receive-true-vote, any] ; 
    ['receive-false-vote, any]),
    delay filter, unlimited) .

do clear memo .

red in ONETHIRDRULE-TEST-SCORE2 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-VU-NARROW-WITH-INV, false),
    'ready['`{_`,_`,_`}['s.Nat, 'OIDS:OidSet, 'INITIAL:InitialObjectSet]],
    'ready['`{_`,_`,_`}['s.Nat,'OIDS':OidSet,'__['CONF:Configuration,
    '<_:_|_>['O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Bool']]]]]],
    (['vote-true, any] ; 
    ['vote-false, any] ; 
    ['receive-true-vote, any] ; 
    ['receive-false-vote, any]),
    delay filter, unlimited) .

do clear memo .

red in ONETHIRDRULE-TEST-SCORE1 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-VU-NARROW-WITH-INV, false),
    'ready['`{_`,_`,_`}['s.Nat, 'OIDS:OidSet, 'INITIAL:InitialObjectSet]],
    'ready['`{_`,_`,_`}['s.Nat,'OIDS':OidSet,'__['CONF:Configuration,
    '<_:_|_>['O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Bool']]]]]],
    (['vote-true, any] ; 
    ['vote-false, any] ; 
    ['receive-true-vote, any] ; 
    ['receive-false-vote, any]),
    delay filter, unlimited) .

do clear memo .


red in ONETHIRDRULE-TEST-SCORE3 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-VU-NARROW-WITH-INV, false),
    'ready['`{_`,_`,_`}['__['s.Nat,'s.Nat], 'OIDS:OidSet, 'INITIAL:InitialObjectSet]],
    'ready['`{_`,_`,_`}['__['s.Nat,'s.Nat],'OIDS':OidSet,'__[
    'CONF:Configuration,'<_:_|_>['O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_[
    'true.Bool']]]]]],
    (['vote-true, any] ; 
    ['vote-false, any] ; 
    ['receive-true-vote, any] ; 
    ['receive-false-vote, any]),
    delay filter, unlimited) .

do clear memo .

red in ONETHIRDRULE-TEST-SCORE2 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-VU-NARROW-WITH-INV, false),
    'ready['`{_`,_`,_`}['__['s.Nat,'s.Nat], 'OIDS:OidSet, 'INITIAL:InitialObjectSet]],
    'ready['`{_`,_`,_`}['__['s.Nat,'s.Nat],'OIDS':OidSet,'__[
    'CONF:Configuration,'<_:_|_>['O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_[
    'true.Bool']]]]]],
    (['vote-true, any] ; 
    ['vote-false, any] ; 
    ['receive-true-vote, any] ; 
    ['receive-false-vote, any]),
    delay filter, unlimited) .

do clear memo .

red in ONETHIRDRULE-TEST-SCORE1 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-VU-NARROW-WITH-INV, false),
    'ready['`{_`,_`,_`}['__['s.Nat,'s.Nat], 'OIDS:OidSet, 'INITIAL:InitialObjectSet]],
    'ready['`{_`,_`,_`}['__['s.Nat,'s.Nat],'OIDS':OidSet,'__[
    'CONF:Configuration,'<_:_|_>['O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_[
    'true.Bool']]]]]],
    (['vote-true, any] ; 
    ['vote-false, any] ; 
    ['receive-true-vote, any] ; 
    ['receive-false-vote, any]),
    delay filter, unlimited) .

do clear memo .


red in ONETHIRDRULE-TEST-SCORE3 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-VU-NARROW-WITH-INV, false),
    'ready['`{_`,_`,_`}['__['s.Nat,'s.Nat,'s.Nat], 'OIDS:OidSet, 'INITIAL:InitialObjectSet]],
    'ready['`{_`,_`,_`}['__['s.Nat,'s.Nat,'s.Nat],'OIDS':OidSet,'__[
    'CONF:Configuration,'<_:_|_>['O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_[
    'true.Bool']]]]]],
    (['vote-true, any] ; 
    ['vote-false, any] ; 
    ['receive-true-vote, any] ; 
    ['receive-false-vote, any]),
    delay filter, unlimited) .

do clear memo .

red in ONETHIRDRULE-TEST-SCORE2 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-VU-NARROW-WITH-INV, false),
    'ready['`{_`,_`,_`}['__['s.Nat,'s.Nat,'s.Nat], 'OIDS:OidSet, 'INITIAL:InitialObjectSet]],
    'ready['`{_`,_`,_`}['__['s.Nat,'s.Nat,'s.Nat],'OIDS':OidSet,'__[
    'CONF:Configuration,'<_:_|_>['O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_[
    'true.Bool']]]]]],
    (['vote-true, any] ; 
    ['vote-false, any] ; 
    ['receive-true-vote, any] ; 
    ['receive-false-vote, any]),
    delay filter, unlimited) .

do clear memo .

red in ONETHIRDRULE-TEST-SCORE1 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-VU-NARROW-WITH-INV, false),
    'ready['`{_`,_`,_`}['__['s.Nat,'s.Nat,'s.Nat], 'OIDS:OidSet, 'INITIAL:InitialObjectSet]],
    'ready['`{_`,_`,_`}['__['s.Nat,'s.Nat,'s.Nat],'OIDS':OidSet,'__[
    'CONF:Configuration,'<_:_|_>['O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_[
    'true.Bool']]]]]],
    (['vote-true, any] ; 
    ['vote-false, any] ; 
    ['receive-true-vote, any] ; 
    ['receive-false-vote, any]),
    delay filter, unlimited) .
