load ../heuristic-search/main.maude
load ./model-extensions/onethirdrule-vu-narrow-index.maude
load ./model-extensions/onethirdrule-vu-narrow-scoring-functions.maude
load ./model-extensions/onethirdrule-vu-narrow-invariant.maude


mod ONETHIRDRULE-TEST-SCORE1 is
    protecting ONETHIRDRULE-VU-NARROW-INDEX .
    protecting ONETHIRDRULE-VU-NARROW-SCORE1 .
    protecting HEURISTIC-NARROWING .
endm

mod ONETHIRDRULE-TEST-SCORE2 is
    protecting ONETHIRDRULE-VU-NARROW-INDEX .
    protecting ONETHIRDRULE-VU-NARROW-SCORE2 .
    protecting HEURISTIC-NARROWING .
endm

mod ONETHIRDRULE-TEST-SCORE3 is
    protecting ONETHIRDRULE-VU-NARROW-INDEX .
    protecting ONETHIRDRULE-VU-NARROW-SCORE3 .
    protecting HEURISTIC-NARROWING .
endm

*** TODO: Add more tests for each scoring function
*** s ss sss decisio
***    upTerm(ready({s s s, OIDS',
***    < O : Node | decision : true, ATTS:U124S >
***    CONF})),

red in ONETHIRDRULE-TEST-SCORE3 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-VU-NARROW-INVARIANT-HALF, false),
    'ready['`{_`,_`,_`}['s.Nat, 'OIDS:OidSet, 'INITIAL:InitialObjectSet]],
    'ready['`{_`,_`,_`}['s.Nat,'OIDS':OidSet,'__['CONF:Configuration,
    '<_:_|_>['O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.FvpBool]]]]]],
    (['vote-true, any] ; 
    ['vote-false, any] ; 
    ['receive-true-vote, any] ; 
    ['receive-false-vote, any]),
    delay filter) .

do clear memo .

red in ONETHIRDRULE-TEST-SCORE3 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-VU-NARROW-INVARIANT-HALF, false),
    'ready['`{_`,_`,_`}['__['s.Nat,'s.Nat], 'OIDS:OidSet, 'INITIAL:InitialObjectSet]],
    'ready['`{_`,_`,_`}['__['s.Nat,'s.Nat],'OIDS':OidSet,'__[
    'CONF:Configuration,'<_:_|_>['O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_[
    'true.FvpBool]]]]]],
    (['vote-true, any] ; 
    ['vote-false, any] ; 
    ['receive-true-vote, any] ; 
    ['receive-false-vote, any]),
    delay filter) .

do clear memo .

red in ONETHIRDRULE-TEST-SCORE3 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-VU-NARROW-INVARIANT-HALF, false),
    'ready['`{_`,_`,_`}['__['s.Nat,'s.Nat,'s.Nat], 'OIDS:OidSet, 'INITIAL:InitialObjectSet]],
    'ready['`{_`,_`,_`}['__['s.Nat,'s.Nat,'s.Nat],'OIDS':OidSet,'__[
    'CONF:Configuration,'<_:_|_>['O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_[
    'true.FvpBool]]]]]],
    (['vote-true, any] ; 
    ['vote-false, any] ; 
    ['receive-true-vote, any] ; 
    ['receive-false-vote, any]),
    delay filter) .

do clear memo .

red in ONETHIRDRULE-TEST-SCORE2 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-VU-NARROW-INVARIANT-HALF, false),
    'ready['`{_`,_`,_`}['s.Nat, 'OIDS:OidSet, 'INITIAL:InitialObjectSet]],
    'ready['`{_`,_`,_`}['s.Nat,'OIDS':OidSet,'__['CONF:Configuration,
    '<_:_|_>['O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.FvpBool]]]]]],
    (['vote-true, any] ; 
    ['vote-false, any] ; 
    ['receive-true-vote, any] ; 
    ['receive-false-vote, any]),
    delay filter) .

do clear memo .

red in ONETHIRDRULE-TEST-SCORE2 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-VU-NARROW-INVARIANT-HALF, false),
    'ready['`{_`,_`,_`}['__['s.Nat,'s.Nat], 'OIDS:OidSet, 'INITIAL:InitialObjectSet]],
    'ready['`{_`,_`,_`}['__['s.Nat,'s.Nat],'OIDS':OidSet,'__[
    'CONF:Configuration,'<_:_|_>['O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_[
    'true.FvpBool]]]]]],
    (['vote-true, any] ; 
    ['vote-false, any] ; 
    ['receive-true-vote, any] ; 
    ['receive-false-vote, any]),
    delay filter) .

do clear memo .

red in ONETHIRDRULE-TEST-SCORE2 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-VU-NARROW-INVARIANT-HALF, false),
    'ready['`{_`,_`,_`}['__['s.Nat,'s.Nat,'s.Nat], 'OIDS:OidSet, 'INITIAL:InitialObjectSet]],
    'ready['`{_`,_`,_`}['__['s.Nat,'s.Nat,'s.Nat],'OIDS':OidSet,'__[
    'CONF:Configuration,'<_:_|_>['O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_[
    'true.FvpBool]]]]]],
    (['vote-true, any] ; 
    ['vote-false, any] ; 
    ['receive-true-vote, any] ; 
    ['receive-false-vote, any]),
    delay filter) .

do clear memo .

red in ONETHIRDRULE-TEST-SCORE1 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-VU-NARROW-INVARIANT-HALF, false),
    'ready['`{_`,_`,_`}['s.Nat, 'OIDS:OidSet, 'INITIAL:InitialObjectSet]],
    'ready['`{_`,_`,_`}['s.Nat,'OIDS':OidSet,'__['CONF:Configuration,
    '<_:_|_>['O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.FvpBool]]]]]],
    (['vote-true, any] ; 
    ['vote-false, any] ; 
    ['receive-true-vote, any] ; 
    ['receive-false-vote, any]),
    delay filter) .

do clear memo .

red in ONETHIRDRULE-TEST-SCORE1 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-VU-NARROW-INVARIANT-HALF, false),
    'ready['`{_`,_`,_`}['__['s.Nat,'s.Nat], 'OIDS:OidSet, 'INITIAL:InitialObjectSet]],
    'ready['`{_`,_`,_`}['__['s.Nat,'s.Nat],'OIDS':OidSet,'__[
    'CONF:Configuration,'<_:_|_>['O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_[
    'true.FvpBool]]]]]],
    (['vote-true, any] ; 
    ['vote-false, any] ; 
    ['receive-true-vote, any] ; 
    ['receive-false-vote, any]),
    delay filter) .

do clear memo .

red in ONETHIRDRULE-TEST-SCORE1 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-VU-NARROW-INVARIANT-HALF, false),
    'ready['`{_`,_`,_`}['__['s.Nat,'s.Nat,'s.Nat], 'OIDS:OidSet, 'INITIAL:InitialObjectSet]],
    'ready['`{_`,_`,_`}['__['s.Nat,'s.Nat,'s.Nat],'OIDS':OidSet,'__[
    'CONF:Configuration,'<_:_|_>['O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_[
    'true.FvpBool]]]]]],
    (['vote-true, any] ; 
    ['vote-false, any] ; 
    ['receive-true-vote, any] ; 
    ['receive-false-vote, any]),
    delay filter) .

do clear memo .
