load ../heuristic-search/index.maude
load ../heuristic-search/invariant.maude
load ../heuristic-search/main.maude
load ../heuristic-search/score.maude
load ../heuristic-search/state.maude
load ../heuristic-search/term-transformer.maude

mod EXAMPLE-SYSTEM is
    including STATE .

    sort Nat .
    op 0 : -> Nat [ctor] .
    op s : Nat -> Nat [ctor] .

    ops f g : Nat -> State .

    var N : Nat .

    rl [l1]: f(s(N)) => f(N) [narrowing] .
    rl [l2]: g(s(N)) => g(N) [narrowing] .
    rl [l3]: f(s(N)) => g(N) [narrowing] .
endm

mod EXAMPLE-SYSTEM-WITH-INV is
    protecting EXAMPLE-SYSTEM .
    including INVARIANT .

    var N : Nat .

    eq initCond(S:State) = true .
    eq inv(g(s(s(s(N))))) = false .
    eq inv(f(s(s(s(N))))) = false .
endm

fmod EXAMPLE-2-SCORE is
    including SCORE .
    protecting NAT .

    subsort Nat < Score .

    vars N N' : Nat .

    eq le(N, N') = N <= N' .

    var F : Qid .
    var T : Term .
    var D : Nat .

    eq score(F[T], D) = 1 + score(T, D) .
    eq score(T, D) = 1 [owise] .
endfm

mod MAIN is
    protecting HEURISTIC-NARROWING .
    protecting EXAMPLE-2-SCORE .
    protecting DEFAULT-INDEX .
    protecting DEFAULT-TERM-TRANSFORMER .
endm

red in MAIN : metaHeuristicNarrowingSearch(
    upModule('EXAMPLE-SYSTEM-WITH-INV, false),
    'f['X:Nat],
    'g['Y:Nat],
    delay filter) .