load ../heuristic-search/main.maude
load ../models/onethirdrule-vu-narrow.maude
load ./model-extensions/onethirdrule-index.maude
load ./model-extensions/onethirdrule-scoring-functions.maude


mod ONETHIRDRULE-TEST-SCORE1 is
    protecting ONETHIRDRULE-VU-NARROW-INDEX .
    protecting ONETHIRDRULE-VU-NARROW-SCORE1 .
    protecting HEURISTIC-NARROWING .
endm

mod ONETHIRDRULE-TEST-SCORE2 is
    protecting ONETHIRDRULE-VU-NARROW-INDEX .
    protecting ONETHIRDRULE-VU-NARROW-SCORE2 .
    protecting HEURISTIC-NARROWING .
endm

mod ONETHIRDRULE-TEST-SCORE3 is
    protecting ONETHIRDRULE-VU-NARROW-INDEX .
    protecting ONETHIRDRULE-VU-NARROW-SCORE3 .
    protecting HEURISTIC-NARROWING .
endm


red in ONETHIRDRULE-TEST-SCORE3 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-VU-NARROW-HALF, false),
    'ready['`{_`,_`,_`}['N:Nat, 'OIDS:OidSet, 'INITIAL:InitialObjectSet]],
    'ready[
    '`{_`,_`,_`}['N':Nat,'OIDS':OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Bool']]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Bool']]]]]],
    (['vote-true-existing, any] ; 
    ['vote-false-existing, any] ; 
    ['receive-true, any] ; 
    ['receive-false, any]),
    delay filter, unlimited) .

do clear memo .

red in ONETHIRDRULE-TEST-SCORE2 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-VU-NARROW-HALF, false),
    'ready['`{_`,_`,_`}['N:Nat, 'OIDS:OidSet, 'INITIAL:InitialObjectSet]],
    'ready[
    '`{_`,_`,_`}['N':Nat,'OIDS':OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Bool']]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Bool']]]]]],
    (['vote-true-existing, any] ; 
    ['vote-false-existing, any] ; 
    ['receive-true, any] ; 
    ['receive-false, any]),
    delay filter, unlimited) .

do clear memo .

red in ONETHIRDRULE-TEST-SCORE3 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-VU-NARROW-HALF, false),
    'ready['`{_`,_`,_`}['N:Nat, 'OIDS:OidSet, 'INITIAL:InitialObjectSet]],
    'ready[
    '`{_`,_`,_`}['N':Nat,'OIDS':OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Bool']]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Bool']]]]]],
    none,
    delay filter, unlimited) .

do clear memo .

red in ONETHIRDRULE-TEST-SCORE2 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-VU-NARROW-HALF, false),
    'ready['`{_`,_`,_`}['N:Nat, 'OIDS:OidSet, 'INITIAL:InitialObjectSet]],
    'ready[
    '`{_`,_`,_`}['N':Nat,'OIDS':OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Bool']]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Bool']]]]]],
    none,
    delay filter, unlimited) .

