
load ../tool/param.maude
load aux-functions/onethirdrule-index.maude
load aux-functions/onethirdrule-scoring-functions.maude

load ../tool/state.maude
load ../tool/tool.maude

load ../model/onethirdrule.maude


mod MAIN is
    protecting ONETHIRDRULE-ANALYSIS .
    protecting ONETHIRDRULE-INDEX .
    protecting ONETHIRDRULE-SCORE-1 .
    protecting HEURISTIC-NARROWING-DRIVER .

    var TH : Natural .
    vars O O' : Oid .
    var OS : OidSet .
    var INITIAL : InitConfiguration .
    vars ATTS ATTS' : U124S .
    var CF : Configuration .
    vars V1 V2 : Value .
endm

set print attribute on .

red heuristic-narrow {filter delay} in 'ONETHIRDRULE-ANALYSIS : 
      {TH, (s ; s s), OS, INITIAL} 
  =>* {TH, (s ; s s), OS, < O  : Node | decision : s, ATTS  >
               < O' : Node | decision : s s, ATTS' > CF}
  such that noDupl(OS) and noDupl(getOids(INITIAL)) and 
            sameRound(getRounds(INITIAL)) and valid1/2(numObjs(INITIAL), TH) 
            and validVMS((s ; s s), getVoteMaps(INITIAL)) .
