load ../../heuristic-search/param.maude
load ../aux-functions/onethirdrule-index.maude
load ../aux-functions/onethirdrule-scoring-functions.maude

load ../../heuristic-search/constraint.maude
load ../../heuristic-search/tool.maude

load ../../models/onethirdrule.maude


mod DRIVER1 is
    protecting ONETHIRDRULE-WITH-INV-HALF .
    protecting ONETHIRDRULE-INDEX .
    protecting ONETHIRDRULE-SCORE1 .
    protecting HEURISTIC-NARROWING-DRIVER .

    var N : Natural .
    vars O O' : Oid .
    var OS : OidSet .
    var INITIAL : InitConfiguration .
    vars ATTS ATTS' : U124S .
    var CONF : Configuration .
endm

mod DRIVER2 is
    protecting ONETHIRDRULE-WITH-INV-HALF .
    protecting ONETHIRDRULE-INDEX .
    protecting ONETHIRDRULE-SCORE2 .
    protecting HEURISTIC-NARROWING-DRIVER .

    var N : Natural .
    vars O O' : Oid .
    var OS : OidSet .
    var INITIAL : InitConfiguration .
    vars ATTS ATTS' : U124S .
    var CONF : Configuration .
endm

mod DRIVER3 is
    protecting ONETHIRDRULE-WITH-INV-HALF .
    protecting ONETHIRDRULE-INDEX .
    protecting ONETHIRDRULE-SCORE3 .
    protecting HEURISTIC-NARROWING-DRIVER .

    var N : Natural .
    vars O O' : Oid .
    var OS : OidSet .
    var INITIAL : InitConfiguration .
    vars ATTS ATTS' : U124S .
    var CONF : Configuration .
endm

mod DRIVER4 is
    protecting ONETHIRDRULE-WITH-INV-HALF .
    protecting ONETHIRDRULE-INDEX .
    protecting ONETHIRDRULE-SCORE4 .
    protecting HEURISTIC-NARROWING-DRIVER .

    var N : Natural .
    vars O O' : Oid .
    var OS : OidSet .
    var INITIAL : InitConfiguration .
    vars ATTS ATTS' : U124S .
    var CONF : Configuration .
endm

mod DRIVER5 is
    protecting ONETHIRDRULE-WITH-INV-HALF .
    protecting ONETHIRDRULE-INDEX .
    protecting ONETHIRDRULE-SCORE5 .
    protecting HEURISTIC-NARROWING-DRIVER .

    var N : Natural .
    vars O O' : Oid .
    var OS : OidSet .
    var INITIAL : InitConfiguration .
    vars ATTS ATTS' : U124S .
    var CONF : Configuration .
endm



red in DRIVER5 : 
heuristic-narrow {filter delay} in  'ONETHIRDRULE-WITH-INV-HALF : 
      {N, OS, INITIAL} 
  =>* {N, OS, < O  : Node | decision : true,  ATTS  >
              < O' : Node | decision : false, ATTS' > CONF}
  such that initCond({N, OS, INITIAL}) .

do clear memo .

red in DRIVER4 : 
heuristic-narrow {filter delay} in  'ONETHIRDRULE-WITH-INV-HALF : 
      {N, OS, INITIAL} 
  =>* {N, OS, < O  : Node | decision : true,  ATTS  >
              < O' : Node | decision : false, ATTS' > CONF}
  such that initCond({N, OS, INITIAL}) .

do clear memo .

red in DRIVER3 : 
heuristic-narrow {filter delay} in  'ONETHIRDRULE-WITH-INV-HALF : 
      {N, OS, INITIAL} 
  =>* {N, OS, < O  : Node | decision : true,  ATTS  >
              < O' : Node | decision : false, ATTS' > CONF}
  such that initCond({N, OS, INITIAL}) .

do clear memo .

red in DRIVER2 : 
heuristic-narrow {filter delay} in  'ONETHIRDRULE-WITH-INV-HALF : 
      {N, OS, INITIAL} 
  =>* {N, OS, < O  : Node | decision : true,  ATTS  >
              < O' : Node | decision : false, ATTS' > CONF}
  such that initCond({N, OS, INITIAL}) .

do clear memo .

red in DRIVER1 : 
heuristic-narrow {filter delay} in  'ONETHIRDRULE-WITH-INV-HALF : 
      {N, OS, INITIAL} 
  =>* {N, OS, < O  : Node | decision : true,  ATTS  >
              < O' : Node | decision : false, ATTS' > CONF}
  such that initCond({N, OS, INITIAL}) .

do clear memo .