
mod ONETHIRDRULE-TERM-TRANSFORMER is
    protecting TERM-TRANSFORMER .
    protecting META-LEVEL .

    op trTerm : Module NeTermList -> NeTermList .

    var M : Module .

    var T : Term .
    var NETL : NeTermList .
    var F : Qid .
    var V : Variable .
    

    eq trTerm(M, F[NETL]) = F[trTerm(M, NETL)] .
    eq trTerm(M, (T, NETL)) = trTerm(M, T), trTerm(M, NETL) .
    eq trTerm(M, empty) = empty .

    ceq trTerm(M, V) = '0.FZero if leastSort(M, V) == 'FZero .

    eq trTerm(M, T) = T [owise] .
endm
