load ../../models/onethirdrule-vu-narrow.maude

{fold} vu-narrow {filter,delay} [1] in ONETHIRDRULE-VU-NARROW-FIXED-OBJS :
{s s, O1 ; O2 ; O3, 
< O1 : Node | status : [R, init], value : V1, decision : nil, votes : [0, 0, 0] >
< O2 : Node | status : [R, init], value : V2, decision : nil, votes : [0, 0, 0] >
< O3 : Node | status : [R, init], value : V3, decision : nil, votes : [0, 0, 0] >}
|| inv(
{s s, O1 ; O2 ; O3, 
< O1 : Node | status : [R, init], value : V1, decision : nil, votes : [0, 0, 0] >
< O2 : Node | status : [R, init], value : V2, decision : nil, votes : [0, 0, 0] >
< O3 : Node | status : [R, init], value : V3, decision : nil, votes : [0, 0, 0] >}
)
=>* 
{N, OS,
< O : Node | decision : true, ATTS:U124S >
< O' : Node | decision : false, ATTS':U124S >
CONF} || INV .
