load ../models/onethirdrule-vu-narrow.maude

vu-narrow {filter,delay} [, 1]  in ONETHIRDRULE-VU-NARROW-HALF :
{N:Natural, OIDS:OidSet, INITIAL:InitialObjectSet}
|| inv({N:Natural, OIDS:OidSet, INITIAL:InitialObjectSet})
=>* none .

vu-narrow {filter,delay} [, 2]  in ONETHIRDRULE-VU-NARROW-HALF :
{N:Natural, OIDS:OidSet, INITIAL:InitialObjectSet}
|| inv({N:Natural, OIDS:OidSet, INITIAL:InitialObjectSet})
=>* none .

vu-narrow {filter,delay} [, 3] in ONETHIRDRULE-VU-NARROW-HALF :
{N:Natural, OIDS:OidSet, INITIAL:InitialObjectSet}
|| inv({N:Natural, OIDS:OidSet, INITIAL:InitialObjectSet})
=>* none .

vu-narrow {filter,delay} [, 4] in ONETHIRDRULE-VU-NARROW-HALF :
{N:Natural, OIDS:OidSet, INITIAL:InitialObjectSet}
|| inv({N:Natural, OIDS:OidSet, INITIAL:InitialObjectSet})
=>* none .

vu-narrow {filter,delay} [, 5] in ONETHIRDRULE-VU-NARROW-HALF :
{N:Natural, OIDS:OidSet, INITIAL:InitialObjectSet}
|| inv({N:Natural, OIDS:OidSet, INITIAL:InitialObjectSet})
=>* none .

vu-narrow {filter,delay} [, 6] in ONETHIRDRULE-VU-NARROW-HALF :
{N:Natural, OIDS:OidSet, INITIAL:InitialObjectSet}
|| inv({N:Natural, OIDS:OidSet, INITIAL:InitialObjectSet})
=>* none .