fmod ONETHIRDRULE-INDEX-AUX is
    including META-TERM .

    vars T : Term .
    var NTL : NeTermList .
    vars N N' : Nat .
    var CI : ConfigInfo .

    sort ConfigInfo .
    op {_,_} : Nat Nat -> ConfigInfo [ctor] .

    op getInfo : NeTermList ConfigInfo -> ConfigInfo .
    eq getInfo('__[NTL], CI) = getInfo(NTL, CI) .
    eq getInfo((T, NTL), CI) = getInfo(NTL, getInfo(T, CI)) .
    eq getInfo('multicast_from_to_[NTL], {N, N'}) = {s(N), N'} .
    eq getInfo('<_:_|_>[NTL], {N, N'}) = {N, s(N')} .
    eq getInfo(T, CI) = CI [owise] .
endfm


fmod ONETHIRDRULE-INDEX is
    including INDEX .
    including ONETHIRDRULE-INDEX-AUX .

    op [_:_] : Qid ConfigInfo -> Index [ctor] .

    vars T TN TNV TO TV TB TOBJ TCF : Term .
    var F : Qid .
    var TL : TermList .

    eq index(F[TV, TB, TNV, TN, TO, TOBJ, TCF]) = [F : getInfo((TOBJ, TCF), {0,0})] .
    eq index(F[TN, TNV, TO, TCF]) = [F : getInfo(TCF, {0,0})] .
endfm


mod ONETHIRDRULE-VU-NARROW-INDEX is
    including INDEX .
    including ONETHIRDRULE-INDEX-AUX .

    op [_,_:_] : Qid Qid ConfigInfo -> Index [ctor] .

    vars T TN TO TV TB TOBJ TCF : Term .
    vars F F' : Qid .
    vars TL : TermList .

    ---FIXME: The following seems incorrect. Where is _||_ ?
    eq index(F'[F[TV, TB, TN, TO, TOBJ, TCF]]) = [F', F : getInfo((TOBJ, TCF), {0,0})] .
    eq index(F'[F[TN, TO, TCF]]) = [F', F : getInfo(TCF, {0,0})] .
endm
