load ../../../models/onethirdrule-vu-narrow.maude

{fold} vu-narrow {filter,delay} in ONETHIRDRULE-VU-NARROW-FIXED-OBJS :
{s s s, O1 ; O2 ; O3, 
< O1 : Node | status : [R, init], value : V1, decision : nil, votes : [0, 0, 0] >
< O2 : Node | status : [R, init], value : V2, decision : nil, votes : [0, 0, 0] >
< O3 : Node | status : [R, init], value : V3, decision : nil, votes : [0, 0, 0] >}
|| inv(
{s s s, O1 ; O2 ; O3, 
< O1 : Node | status : [R, init], value : V1, decision : nil, votes : [0, 0, 0] >
< O2 : Node | status : [R, init], value : V2, decision : nil, votes : [0, 0, 0] >
< O3 : Node | status : [R, init], value : V3, decision : nil, votes : [0, 0, 0] >}
)
=>* S:State .
