load ../../../models/onethirdrule-vu-narrow.maude

vu-narrow {filter,delay} [, 1]  in ONETHIRDRULE-VU-NARROW-TWOTHIRD :
{N, OS, INITIAL}
|| inv({N, OS, INITIAL})
=>* unreachable .

vu-narrow {filter,delay} [, 2]  in ONETHIRDRULE-VU-NARROW-TWOTHIRD :
{N, OS, INITIAL}
|| inv({N, OS, INITIAL})
=>* unreachable .

vu-narrow {filter,delay} [, 3] in ONETHIRDRULE-VU-NARROW-TWOTHIRD :
{N, OS, INITIAL}
|| inv({N, OS, INITIAL})
=>* unreachable .

vu-narrow {filter,delay} [, 4] in ONETHIRDRULE-VU-NARROW-TWOTHIRD :
{N, OS, INITIAL}
|| inv({N, OS, INITIAL})
=>* unreachable .

vu-narrow {filter,delay} [, 5] in ONETHIRDRULE-VU-NARROW-TWOTHIRD :
{N, OS, INITIAL}
|| inv({N, OS, INITIAL})
=>* unreachable .

vu-narrow {filter,delay} [, 6] in ONETHIRDRULE-VU-NARROW-TWOTHIRD :
{N, OS, INITIAL}
|| inv({N, OS, INITIAL})
=>* unreachable .

vu-narrow {filter,delay} [, 7] in ONETHIRDRULE-VU-NARROW-TWOTHIRD :
{N, OS, INITIAL}
|| inv({N, OS, INITIAL})
=>* unreachable .