
set include BOOL off . 

fmod FVP-BOOL is
    sort Boolean True False .
    subsorts True False < Boolean .
    op true : -> True [ctor] .
    op false : -> False [ctor] .
    op _and_ : Boolean Boolean -> Boolean [assoc comm] .

    vars B  X : Boolean .

    eq true and B = B [variant] .
    eq false and B = false [variant] .
    eq B and B = B [variant] .
    eq B and B and X = B and X [variant] . --- for coherence completion
endfm
