load ../main.maude

red in TEST-1 : 
heuristic-narrow {filter delay} in 'ONETHIRDRULE-NML-ANALYSIS : 
      {s, (0 ; s), OS, INITIAL} 
  =>* {s, (0 ; s), OS, < O  : Node | decision : 0, ATTS  >
               < O' : Node | decision : s, ATTS' > CF}
  such that noDupl(OS) and noDupl(getOids(INITIAL)) and 
            sameRound(getRounds(INITIAL)) 
            and validVMS((0 ; s), getVoteMaps(INITIAL)) .

do clear memo .

red in TEST-2 : 
heuristic-narrow {filter delay} in 'ONETHIRDRULE-NML-ANALYSIS : 
      {s, (0 ; s), OS, INITIAL} 
  =>* {s, (0 ; s), OS, < O  : Node | decision : 0, ATTS  >
               < O' : Node | decision : s, ATTS' > CF}
  such that noDupl(OS) and noDupl(getOids(INITIAL)) and 
            sameRound(getRounds(INITIAL)) 
            and validVMS((0 ; s), getVoteMaps(INITIAL)) .

do clear memo .

red in TEST-3 : 
heuristic-narrow {filter delay} in 'ONETHIRDRULE-NML-ANALYSIS : 
      {s, (0 ; s), OS, INITIAL} 
  =>* {s, (0 ; s), OS, < O  : Node | decision : 0, ATTS  >
               < O' : Node | decision : s, ATTS' > CF}
  such that noDupl(OS) and noDupl(getOids(INITIAL)) and 
            sameRound(getRounds(INITIAL)) 
            and validVMS((0 ; s), getVoteMaps(INITIAL)) .

do clear memo .

red in TEST-G : 
heuristic-narrow {filter delay} in 'ONETHIRDRULE-NML-ANALYSIS : 
      {s, (0 ; s), OS, INITIAL} 
  =>* {s, (0 ; s), OS, < O  : Node | decision : 0, ATTS  >
               < O' : Node | decision : s, ATTS' > CF}
  such that noDupl(OS) and noDupl(getOids(INITIAL)) and 
            sameRound(getRounds(INITIAL)) 
            and validVMS((0 ; s), getVoteMaps(INITIAL)) .


do clear memo .

red in TEST-BFS : 
heuristic-narrow {filter delay} in 'ONETHIRDRULE-NML-ANALYSIS : 
      {s, (0 ; s), OS, INITIAL} 
  =>* {s, (0 ; s), OS, < O  : Node | decision : 0, ATTS  >
               < O' : Node | decision : s, ATTS' > CF}
  such that noDupl(OS) and noDupl(getOids(INITIAL)) and 
            sameRound(getRounds(INITIAL)) 
            and validVMS((0 ; s), getVoteMaps(INITIAL)) .

do clear memo .
