load ../main.maude

red in TEST-1 : 
heuristic-narrow {filter delay} in 'ONETHIRDRULE-NML-ANALYSIS : 
      init3(s s, O1, O2, O3, R, V1, V2, V3)
  =>* {s s, O1 ; O2 ; O3, < O  : Node | decision : v1, ATTS >
               < O' : Node | decision : v2, ATTS' > CF}
  such that noDupl(O1 ; O2 ; O3) .

do clear memo .

red in TEST-2 : 
heuristic-narrow {filter delay} in 'ONETHIRDRULE-NML-ANALYSIS : 
      init3(s s, O1, O2, O3, R, V1, V2, V3)
  =>* {s s, O1 ; O2 ; O3, < O  : Node | decision : v1, ATTS >
               < O' : Node | decision : v2, ATTS' > CF}
  such that noDupl(O1 ; O2 ; O3) .

do clear memo .

red in TEST-3 : 
heuristic-narrow {filter delay} in 'ONETHIRDRULE-NML-ANALYSIS : 
      init3(s s, O1, O2, O3, R, V1, V2, V3)
  =>* {s s, O1 ; O2 ; O3, < O  : Node | decision : v1, ATTS >
               < O' : Node | decision : v2, ATTS' > CF}
  such that noDupl(O1 ; O2 ; O3) .

do clear memo .

red in TEST-G : 
heuristic-narrow {filter delay} in 'ONETHIRDRULE-NML-ANALYSIS : 
      init3(s s, O1, O2, O3, R, V1, V2, V3)
  =>* {s s, O1 ; O2 ; O3, < O  : Node | decision : v1, ATTS >
               < O' : Node | decision : v2, ATTS' > CF}
  such that noDupl(O1 ; O2 ; O3) .

do clear memo .

red in TEST-BFS : 
heuristic-narrow {filter delay} in 'ONETHIRDRULE-NML-ANALYSIS : 
      init3(s s, O1, O2, O3, R, V1, V2, V3)
  =>* {s s, O1 ; O2 ; O3, < O  : Node | decision : v1, ATTS >
               < O' : Node | decision : v2, ATTS' > CF}
  such that noDupl(O1 ; O2 ; O3) .

do clear memo .

