load ../main.maude

red in TEST-1 : 
heuristic-narrow {filter delay} in 'ONETHIRDRULE-ANALYSIS : 
      init3(s, O1, O2, O3, R, V1, V2, V3)
  =>* {s, O1 ; O2 ; O3, < O  : Node | decision : true, ATTS >
               < O' : Node | decision : false, ATTS' > CF}
  such that true .

do clear memo .

red in TEST-2 : 
heuristic-narrow {filter delay} in 'ONETHIRDRULE-ANALYSIS : 
      init3(s, O1, O2, O3, R, V1, V2, V3)
  =>* {s, O1 ; O2 ; O3, < O  : Node | decision : true, ATTS >
               < O' : Node | decision : false, ATTS' > CF}
  such that true .

do clear memo .

red in TEST-3 : 
heuristic-narrow {filter delay} in 'ONETHIRDRULE-ANALYSIS : 
      init3(s, O1, O2, O3, R, V1, V2, V3)
  =>* {s, O1 ; O2 ; O3, < O  : Node | decision : true, ATTS >
               < O' : Node | decision : false, ATTS' > CF}
  such that true .

do clear memo .

red in TEST-G : 
heuristic-narrow {filter delay} in 'ONETHIRDRULE-ANALYSIS : 
      init3(s, O1, O2, O3, R, V1, V2, V3)
  =>* {s, O1 ; O2 ; O3, < O  : Node | decision : true, ATTS >
               < O' : Node | decision : false, ATTS' > CF}
  such that true .

do clear memo .

red in TEST-BFS : 
heuristic-narrow {filter delay} in 'ONETHIRDRULE-ANALYSIS : 
      init3(s, O1, O2, O3, R, V1, V2, V3)
  =>* {s, O1 ; O2 ; O3, < O  : Node | decision : true, ATTS >
               < O' : Node | decision : false, ATTS' > CF}
  such that true .

do clear memo .

