load ../../../models/onethirdrule-vu-narrow.maude

{fold} vu-narrow {filter, delay} [, 1] in ONETHIRDRULE-VU-NARROW-HALF :
{N, OS, INITIAL}
|| inv({N, OS, INITIAL})
=>* S:State .

{fold} vu-narrow {filter, delay} [, 2] in ONETHIRDRULE-VU-NARROW-HALF :
{N, OS, INITIAL}
|| inv({N, OS, INITIAL})
=>* S:State .

{fold} vu-narrow {filter, delay} [, 3] in ONETHIRDRULE-VU-NARROW-HALF :
{N, OS, INITIAL}
|| inv({N, OS, INITIAL})
=>* S:State .

{fold} vu-narrow {filter, delay} [, 4] in ONETHIRDRULE-VU-NARROW-HALF :
{N, OS, INITIAL}
|| inv({N, OS, INITIAL})
=>* S:State .

{fold} vu-narrow {filter, delay} [, 5] in ONETHIRDRULE-VU-NARROW-HALF :
{N, OS, INITIAL}
|| inv({N, OS, INITIAL})
=>* S:State .

{fold} vu-narrow {filter, delay} [, 6] in ONETHIRDRULE-VU-NARROW-HALF :
{N, OS, INITIAL}
|| inv({N, OS, INITIAL})
=>* S:State .

{fold} vu-narrow {filter, delay} [, 7] in ONETHIRDRULE-VU-NARROW-HALF :
{N, OS, INITIAL}
|| inv({N, OS, INITIAL})
=>* S:State .
