load ../../heuristic-search/main.maude
load ../aux-functions/onethirdrule-index.maude
load ../aux-functions/onethirdrule-scoring-functions.maude
load ../aux-functions/onethirdrule-term-transformer.maude


mod DRIVER1 is
    protecting ONETHIRDRULE-INDEX .
    protecting ONETHIRDRULE-TERM-TRANSFORMER .
    protecting ONETHIRDRULE-SCORE1 .
    protecting HEURISTIC-NARROWING .
endm

*** no reduction
load ../../models/no-message-loss.maude

red in DRIVER1 : metaHeuristicNarrowingSearch(
    upModule('NO-MESSAGE-LOSS-TWOTHIRD, false),
    '`{_`,_`,_`}['N:Natural, 'OS:OidSet, 'INITIAL:InitConfiguration],
    '`{_`,_`,_`}['N':Natural,'OS':OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    none, delay filter, 1) .

do clear memo .

red in DRIVER1 : metaHeuristicNarrowingSearch(
    upModule('NO-MESSAGE-LOSS-TWOTHIRD, false),
    '`{_`,_`,_`}['N:Natural, 'OS:OidSet, 'INITIAL:InitConfiguration],
    '`{_`,_`,_`}['N':Natural,'OS':OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    none, delay filter, 2) .

do clear memo .

red in DRIVER1 : metaHeuristicNarrowingSearch(
    upModule('NO-MESSAGE-LOSS-TWOTHIRD, false),
    '`{_`,_`,_`}['N:Natural, 'OS:OidSet, 'INITIAL:InitConfiguration],
    '`{_`,_`,_`}['N':Natural,'OS':OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    none, delay filter, 3) .

do clear memo .

red in DRIVER1 : metaHeuristicNarrowingSearch(
    upModule('NO-MESSAGE-LOSS-TWOTHIRD, false),
    '`{_`,_`,_`}['N:Natural, 'OS:OidSet, 'INITIAL:InitConfiguration],
    '`{_`,_`,_`}['N':Natural,'OS':OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    none, delay filter, 4) .

do clear memo .

red in DRIVER1 : metaHeuristicNarrowingSearch(
    upModule('NO-MESSAGE-LOSS-TWOTHIRD, false),
    '`{_`,_`,_`}['N:Natural, 'OS:OidSet, 'INITIAL:InitConfiguration],
    '`{_`,_`,_`}['N':Natural,'OS':OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    none, delay filter, 5) .

do clear memo .

red in DRIVER1 : metaHeuristicNarrowingSearch(
    upModule('NO-MESSAGE-LOSS-TWOTHIRD, false),
    '`{_`,_`,_`}['N:Natural, 'OS:OidSet, 'INITIAL:InitConfiguration],
    '`{_`,_`,_`}['N':Natural,'OS':OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    none, delay filter, 6) .

do clear memo .

*** static reduction
load ../../models/no-message-loss-static.maude

red in DRIVER1 : metaHeuristicNarrowingSearch(
    upModule('NO-MESSAGE-LOSS-STATIC-TWOTHIRD, false),
    '`{_`,_`,_`}['N:Natural, 'OS:OidSet, 'INITIAL:InitConfiguration],
    '`{_`,_`,_`}['N':Natural,'OS':OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    none, delay filter, 1) .

do clear memo .

red in DRIVER1 : metaHeuristicNarrowingSearch(
    upModule('NO-MESSAGE-LOSS-STATIC-TWOTHIRD, false),
    '`{_`,_`,_`}['N:Natural, 'OS:OidSet, 'INITIAL:InitConfiguration],
    '`{_`,_`,_`}['N':Natural,'OS':OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    none, delay filter, 2) .

do clear memo .

red in DRIVER1 : metaHeuristicNarrowingSearch(
    upModule('NO-MESSAGE-LOSS-STATIC-TWOTHIRD, false),
    '`{_`,_`,_`}['N:Natural, 'OS:OidSet, 'INITIAL:InitConfiguration],
    '`{_`,_`,_`}['N':Natural,'OS':OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    none, delay filter, 3) .

do clear memo .

red in DRIVER1 : metaHeuristicNarrowingSearch(
    upModule('NO-MESSAGE-LOSS-STATIC-TWOTHIRD, false),
    '`{_`,_`,_`}['N:Natural, 'OS:OidSet, 'INITIAL:InitConfiguration],
    '`{_`,_`,_`}['N':Natural,'OS':OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    none, delay filter, 4) .

do clear memo .

red in DRIVER1 : metaHeuristicNarrowingSearch(
    upModule('NO-MESSAGE-LOSS-STATIC-TWOTHIRD, false),
    '`{_`,_`,_`}['N:Natural, 'OS:OidSet, 'INITIAL:InitConfiguration],
    '`{_`,_`,_`}['N':Natural,'OS':OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    none, delay filter, 5) .

do clear memo .

red in DRIVER1 : metaHeuristicNarrowingSearch(
    upModule('NO-MESSAGE-LOSS-STATIC-TWOTHIRD, false),
    '`{_`,_`,_`}['N:Natural, 'OS:OidSet, 'INITIAL:InitConfiguration],
    '`{_`,_`,_`}['N':Natural,'OS':OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    none, delay filter, 6) .

do clear memo .

*** static + dynamic reduction
load ../../models/no-message-loss-static-dynamic.maude

red in DRIVER1 : metaHeuristicNarrowingSearch(
    upModule('NO-MESSAGE-LOSS-STATIC-DYNAMIC-TWOTHIRD, false),
    '`{_`,_`,_`}['N:Natural, 'OS:OidSet, 'INITIAL:InitConfiguration],
    '`{_`,_`,_`}['N':Natural,'OS':OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    'vote-by-existing ; 'receive, 
    delay filter, 1) .

do clear memo .

red in DRIVER1 : metaHeuristicNarrowingSearch(
    upModule('NO-MESSAGE-LOSS-STATIC-DYNAMIC-TWOTHIRD, false),
    '`{_`,_`,_`}['N:Natural, 'OS:OidSet, 'INITIAL:InitConfiguration],
    '`{_`,_`,_`}['N':Natural,'OS':OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    'vote-by-existing ; 'receive, 
    delay filter, 2) .

do clear memo .

red in DRIVER1 : metaHeuristicNarrowingSearch(
    upModule('NO-MESSAGE-LOSS-STATIC-DYNAMIC-TWOTHIRD, false),
    '`{_`,_`,_`}['N:Natural, 'OS:OidSet, 'INITIAL:InitConfiguration],
    '`{_`,_`,_`}['N':Natural,'OS':OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    'vote-by-existing ; 'receive, 
    delay filter, 3) .

do clear memo .

red in DRIVER1 : metaHeuristicNarrowingSearch(
    upModule('NO-MESSAGE-LOSS-STATIC-DYNAMIC-TWOTHIRD, false),
    '`{_`,_`,_`}['N:Natural, 'OS:OidSet, 'INITIAL:InitConfiguration],
    '`{_`,_`,_`}['N':Natural,'OS':OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    'vote-by-existing ; 'receive, 
    delay filter, 4) .

do clear memo .

red in DRIVER1 : metaHeuristicNarrowingSearch(
    upModule('NO-MESSAGE-LOSS-STATIC-DYNAMIC-TWOTHIRD, false),
    '`{_`,_`,_`}['N:Natural, 'OS:OidSet, 'INITIAL:InitConfiguration],
    '`{_`,_`,_`}['N':Natural,'OS':OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    'vote-by-existing ; 'receive, 
    delay filter, 5) .

do clear memo .

red in DRIVER1 : metaHeuristicNarrowingSearch(
    upModule('NO-MESSAGE-LOSS-STATIC-DYNAMIC-TWOTHIRD, false),
    '`{_`,_`,_`}['N:Natural, 'OS:OidSet, 'INITIAL:InitConfiguration],
    '`{_`,_`,_`}['N':Natural,'OS':OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    'vote-by-existing ; 'receive, 
    delay filter, 6) .

do clear memo .