load ../../heuristic-search/main.maude
load ../aux-functions/onethirdrule-index.maude
load ../aux-functions/onethirdrule-scoring-functions.maude
load ../aux-functions/onethirdrule-term-transformer.maude


mod DRIVER1 is
    protecting ONETHIRDRULE-INDEX .
    protecting ONETHIRDRULE-TERM-TRANSFORMER .
    protecting ONETHIRDRULE-SCORE1 .
    protecting HEURISTIC-NARROWING .
endm

mod DRIVER2 is
    protecting ONETHIRDRULE-INDEX .
    protecting ONETHIRDRULE-TERM-TRANSFORMER .
    protecting ONETHIRDRULE-SCORE2 .
    protecting HEURISTIC-NARROWING .
endm

mod DRIVER3 is
    protecting ONETHIRDRULE-INDEX .
    protecting ONETHIRDRULE-TERM-TRANSFORMER .
    protecting ONETHIRDRULE-SCORE3 .
    protecting HEURISTIC-NARROWING .
endm


*** score 3

load ../../models/onethirdrule.maude


red in DRIVER3 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-FIXED-OBJS, false),
    '`{_`,_`,_`}['__['s.Natural,'s.Natural,'s.Natural],'_;_['O1:Oid,
    'O2:Oid,'O3:Oid],'__['<_:_|_>['O1:Oid,'Node.Cid,'_`,_['status`:_['`[_`,_`][
    'R:Natural,'init.InitStep]],'value`:_['V1:Value],'decision`:_[
    'nil.InitValue?],'votes`:_['`[_`,_`,_`]['0.Zero,'0.Zero,'0.Zero]]]],
    '<_:_|_>['O2:Oid,'Node.Cid,'_`,_['status`:_['`[_`,_`]['R:Natural,
    'init.InitStep]],'value`:_['V2:Value],'decision`:_['nil.InitValue?],
    'votes`:_['`[_`,_`,_`]['0.Zero,'0.Zero,'0.Zero]]]],'<_:_|_>['O3:Oid,
    'Node.Cid,'_`,_['status`:_['`[_`,_`]['R:Natural,'init.InitStep]],
    'value`:_['V3:Value],'decision`:_['nil.InitValue?],'votes`:_['`[_`,_`,_`][
    '0.Zero,'0.Zero,'0.Zero]]]]]],
    '`{_`,_`,_`}['N:Natural,'OS:OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    none, delay filter, unlimited) .

do clear memo .

load ../../models/onethirdrule-static.maude

red in DRIVER3 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-STATIC-FIXED-OBJS, false),
    '`{_`,_`,_`}['__['s.Natural,'s.Natural,'s.Natural],'_;_['O1:Oid,
    'O2:Oid,'O3:Oid],'__['<_:_|_>['O1:Oid,'Node.Cid,'_`,_['status`:_['`[_`,_`][
    'R:Natural,'init.InitStep]],'value`:_['V1:Value],'decision`:_[
    'nil.InitValue?],'votes`:_['`[_`,_`,_`]['0.Zero,'0.Zero,'0.Zero]]]],
    '<_:_|_>['O2:Oid,'Node.Cid,'_`,_['status`:_['`[_`,_`]['R:Natural,
    'init.InitStep]],'value`:_['V2:Value],'decision`:_['nil.InitValue?],
    'votes`:_['`[_`,_`,_`]['0.Zero,'0.Zero,'0.Zero]]]],'<_:_|_>['O3:Oid,
    'Node.Cid,'_`,_['status`:_['`[_`,_`]['R:Natural,'init.InitStep]],
    'value`:_['V3:Value],'decision`:_['nil.InitValue?],'votes`:_['`[_`,_`,_`][
    '0.Zero,'0.Zero,'0.Zero]]]]]],
    '`{_`,_`,_`}['N':Natural,'OIDS':OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    none, delay filter, unlimited) .

do clear memo .

load ../../models/onethirdrule-static-dynamic.maude

red in DRIVER3 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-STATIC-DYNAMIC-FIXED-OBJS, false),
    '`{_`,_`,_`}['__['s.Natural,'s.Natural,'s.Natural],'_;_['O1:Oid,
    'O2:Oid,'O3:Oid],'__['<_:_|_>['O1:Oid,'Node.Cid,'_`,_['status`:_['`[_`,_`][
    'R:Natural,'init.InitStep]],'value`:_['V1:Value],'decision`:_[
    'nil.InitValue?],'votes`:_['`[_`,_`,_`]['0.Zero,'0.Zero,'0.Zero]]]],
    '<_:_|_>['O2:Oid,'Node.Cid,'_`,_['status`:_['`[_`,_`]['R:Natural,
    'init.InitStep]],'value`:_['V2:Value],'decision`:_['nil.InitValue?],
    'votes`:_['`[_`,_`,_`]['0.Zero,'0.Zero,'0.Zero]]]],'<_:_|_>['O3:Oid,
    'Node.Cid,'_`,_['status`:_['`[_`,_`]['R:Natural,'init.InitStep]],
    'value`:_['V3:Value],'decision`:_['nil.InitValue?],'votes`:_['`[_`,_`,_`][
    '0.Zero,'0.Zero,'0.Zero]]]]]],
    '`{_`,_`,_`}['N':Natural,'OIDS':OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    'vote-by-existing ; 'receive,
    delay filter, unlimited) .

do clear memo .

*** score 2

load ../../models/onethirdrule.maude


red in DRIVER2 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-FIXED-OBJS, false),
    '`{_`,_`,_`}['__['s.Natural,'s.Natural,'s.Natural],'_;_['O1:Oid,
    'O2:Oid,'O3:Oid],'__['<_:_|_>['O1:Oid,'Node.Cid,'_`,_['status`:_['`[_`,_`][
    'R:Natural,'init.InitStep]],'value`:_['V1:Value],'decision`:_[
    'nil.InitValue?],'votes`:_['`[_`,_`,_`]['0.Zero,'0.Zero,'0.Zero]]]],
    '<_:_|_>['O2:Oid,'Node.Cid,'_`,_['status`:_['`[_`,_`]['R:Natural,
    'init.InitStep]],'value`:_['V2:Value],'decision`:_['nil.InitValue?],
    'votes`:_['`[_`,_`,_`]['0.Zero,'0.Zero,'0.Zero]]]],'<_:_|_>['O3:Oid,
    'Node.Cid,'_`,_['status`:_['`[_`,_`]['R:Natural,'init.InitStep]],
    'value`:_['V3:Value],'decision`:_['nil.InitValue?],'votes`:_['`[_`,_`,_`][
    '0.Zero,'0.Zero,'0.Zero]]]]]],
    '`{_`,_`,_`}['N:Natural,'OS:OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    none, delay filter, unlimited) .

do clear memo .

load ../../models/onethirdrule-static.maude

red in DRIVER2 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-STATIC-FIXED-OBJS, false),
    '`{_`,_`,_`}['__['s.Natural,'s.Natural,'s.Natural],'_;_['O1:Oid,
    'O2:Oid,'O3:Oid],'__['<_:_|_>['O1:Oid,'Node.Cid,'_`,_['status`:_['`[_`,_`][
    'R:Natural,'init.InitStep]],'value`:_['V1:Value],'decision`:_[
    'nil.InitValue?],'votes`:_['`[_`,_`,_`]['0.Zero,'0.Zero,'0.Zero]]]],
    '<_:_|_>['O2:Oid,'Node.Cid,'_`,_['status`:_['`[_`,_`]['R:Natural,
    'init.InitStep]],'value`:_['V2:Value],'decision`:_['nil.InitValue?],
    'votes`:_['`[_`,_`,_`]['0.Zero,'0.Zero,'0.Zero]]]],'<_:_|_>['O3:Oid,
    'Node.Cid,'_`,_['status`:_['`[_`,_`]['R:Natural,'init.InitStep]],
    'value`:_['V3:Value],'decision`:_['nil.InitValue?],'votes`:_['`[_`,_`,_`][
    '0.Zero,'0.Zero,'0.Zero]]]]]],
    '`{_`,_`,_`}['N':Natural,'OIDS':OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    none, delay filter, unlimited) .

do clear memo .

load ../../models/onethirdrule-static-dynamic.maude

red in DRIVER2 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-STATIC-DYNAMIC-FIXED-OBJS, false),
    '`{_`,_`,_`}['__['s.Natural,'s.Natural,'s.Natural],'_;_['O1:Oid,
    'O2:Oid,'O3:Oid],'__['<_:_|_>['O1:Oid,'Node.Cid,'_`,_['status`:_['`[_`,_`][
    'R:Natural,'init.InitStep]],'value`:_['V1:Value],'decision`:_[
    'nil.InitValue?],'votes`:_['`[_`,_`,_`]['0.Zero,'0.Zero,'0.Zero]]]],
    '<_:_|_>['O2:Oid,'Node.Cid,'_`,_['status`:_['`[_`,_`]['R:Natural,
    'init.InitStep]],'value`:_['V2:Value],'decision`:_['nil.InitValue?],
    'votes`:_['`[_`,_`,_`]['0.Zero,'0.Zero,'0.Zero]]]],'<_:_|_>['O3:Oid,
    'Node.Cid,'_`,_['status`:_['`[_`,_`]['R:Natural,'init.InitStep]],
    'value`:_['V3:Value],'decision`:_['nil.InitValue?],'votes`:_['`[_`,_`,_`][
    '0.Zero,'0.Zero,'0.Zero]]]]]],
    '`{_`,_`,_`}['N':Natural,'OIDS':OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    'vote-by-existing ; 'receive,
    delay filter, unlimited) .

do clear memo .

*** score 1

load ../../models/onethirdrule.maude


red in DRIVER1 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-FIXED-OBJS, false),
    '`{_`,_`,_`}['__['s.Natural,'s.Natural,'s.Natural],'_;_['O1:Oid,
    'O2:Oid,'O3:Oid],'__['<_:_|_>['O1:Oid,'Node.Cid,'_`,_['status`:_['`[_`,_`][
    'R:Natural,'init.InitStep]],'value`:_['V1:Value],'decision`:_[
    'nil.InitValue?],'votes`:_['`[_`,_`,_`]['0.Zero,'0.Zero,'0.Zero]]]],
    '<_:_|_>['O2:Oid,'Node.Cid,'_`,_['status`:_['`[_`,_`]['R:Natural,
    'init.InitStep]],'value`:_['V2:Value],'decision`:_['nil.InitValue?],
    'votes`:_['`[_`,_`,_`]['0.Zero,'0.Zero,'0.Zero]]]],'<_:_|_>['O3:Oid,
    'Node.Cid,'_`,_['status`:_['`[_`,_`]['R:Natural,'init.InitStep]],
    'value`:_['V3:Value],'decision`:_['nil.InitValue?],'votes`:_['`[_`,_`,_`][
    '0.Zero,'0.Zero,'0.Zero]]]]]],
    '`{_`,_`,_`}['N:Natural,'OS:OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    none, delay filter, unlimited) .

do clear memo .

load ../../models/onethirdrule-static.maude

red in DRIVER1 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-STATIC-FIXED-OBJS, false),
    '`{_`,_`,_`}['__['s.Natural,'s.Natural,'s.Natural],'_;_['O1:Oid,
    'O2:Oid,'O3:Oid],'__['<_:_|_>['O1:Oid,'Node.Cid,'_`,_['status`:_['`[_`,_`][
    'R:Natural,'init.InitStep]],'value`:_['V1:Value],'decision`:_[
    'nil.InitValue?],'votes`:_['`[_`,_`,_`]['0.Zero,'0.Zero,'0.Zero]]]],
    '<_:_|_>['O2:Oid,'Node.Cid,'_`,_['status`:_['`[_`,_`]['R:Natural,
    'init.InitStep]],'value`:_['V2:Value],'decision`:_['nil.InitValue?],
    'votes`:_['`[_`,_`,_`]['0.Zero,'0.Zero,'0.Zero]]]],'<_:_|_>['O3:Oid,
    'Node.Cid,'_`,_['status`:_['`[_`,_`]['R:Natural,'init.InitStep]],
    'value`:_['V3:Value],'decision`:_['nil.InitValue?],'votes`:_['`[_`,_`,_`][
    '0.Zero,'0.Zero,'0.Zero]]]]]],
    '`{_`,_`,_`}['N':Natural,'OIDS':OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    none, delay filter, unlimited) .

do clear memo .

load ../../models/onethirdrule-static-dynamic.maude

red in DRIVER1 : metaHeuristicNarrowingSearch(
    upModule('ONETHIRDRULE-STATIC-DYNAMIC-FIXED-OBJS, false),
    '`{_`,_`,_`}['__['s.Natural,'s.Natural,'s.Natural],'_;_['O1:Oid,
    'O2:Oid,'O3:Oid],'__['<_:_|_>['O1:Oid,'Node.Cid,'_`,_['status`:_['`[_`,_`][
    'R:Natural,'init.InitStep]],'value`:_['V1:Value],'decision`:_[
    'nil.InitValue?],'votes`:_['`[_`,_`,_`]['0.Zero,'0.Zero,'0.Zero]]]],
    '<_:_|_>['O2:Oid,'Node.Cid,'_`,_['status`:_['`[_`,_`]['R:Natural,
    'init.InitStep]],'value`:_['V2:Value],'decision`:_['nil.InitValue?],
    'votes`:_['`[_`,_`,_`]['0.Zero,'0.Zero,'0.Zero]]]],'<_:_|_>['O3:Oid,
    'Node.Cid,'_`,_['status`:_['`[_`,_`]['R:Natural,'init.InitStep]],
    'value`:_['V3:Value],'decision`:_['nil.InitValue?],'votes`:_['`[_`,_`,_`][
    '0.Zero,'0.Zero,'0.Zero]]]]]],
    '`{_`,_`,_`}['N':Natural,'OIDS':OidSet,'__['CONF:Configuration,'<_:_|_>[
    'O:Oid,'Node.Cid,'_`,_['ATTS:U124S,'decision`:_['true.Boolean]]],'<_:_|_>[
    'O':Oid,'Node.Cid,'_`,_['ATTS':U124S,'decision`:_['false.Boolean]]]]],
    'vote-by-existing ; 'receive,
    delay filter, unlimited) .

do clear memo .