load ./onethirdrule-scoring-functions.maude

fmod ONETHIRDRULE-VU-NARROW-SCORE1 is
    including ONETHIRDRULE-SCORE1 .

    vars T BT : Term . var D : Nat .

    eq score('ready[T], D) = score(T, D) .
    eq score('check[BT, T], D) = score(T, D) .
endfm

fmod ONETHIRDRULE-VU-NARROW-SCORE2 is
    including ONETHIRDRULE-SCORE2 .

    vars T BT : Term . var D : Nat .

    eq score('ready[T], D) = score(T, D) .
    eq score('check[BT, T], D) = score(T, D) .
endfm 

fmod ONETHIRDRULE-VU-NARROW-SCORE3 is
    including ONETHIRDRULE-SCORE3 .

    vars T BT : Term . var D : Nat .

    eq score('ready[T], D) = score(T, D) .
    eq score('check[BT, T], D) = score(T, D) .
endfm 