load ../../heuristic-search/score.maude


fmod ONETHIRDRULE-SCORE1 is
    including SCORE .
    protecting INT .

    subsort Int < Score .

    vars N N' D : Int .
    vars T : Term .

    eq le(N, N') = N <= N' .

    eq score(T, D) = D .
endfm

--- for score2 and score3
fmod ONETHIRDRULE-SCORE-BASE is
    including SCORE .
    protecting INT .

    subsort Int < Score .

    vars N N' : Int .
    vars T BT NT OIDT OT CT ST : Term .
    var D : Nat .
    var NETL : NeTermList .

    eq le(N, N') = N <= N' .

    eq score(
        '`{_`,_`,_`}[T, OIDT, NETL], D
    ) = scoreConf(NETL) .

    op scoreConf : NeTermList -> Score .

    eq scoreConf('__[NETL]) = scoreConf(NETL) .
    eq scoreConf((T, NETL)) 
    = scoreConf(T) + scoreConf(NETL) .


    eq scoreConf(T) = 0 [owise] .

    *** auxiliary functions
    op toNumber : Term -> Int .
    eq toNumber('0.Nat) = 0 .
    eq toNumber('s.Nat) = 1 .
    eq toNumber(T) = 0 [owise] .
    eq toNumber('__[NETL]) = countS(NETL) .

    op countS : NeTermList -> Int .
    eq countS('s.Nat) = 1 .
    eq countS(T) = 0 [owise] .
    eq countS((T, NETL)) = countS(T) + countS(NETL) .
endfm

fmod ONETHIRDRULE-SCORE2 is
    including ONETHIRDRULE-SCORE-BASE .

    vars T BT NT OIDT OT CT ST : Term .
    var D : Nat .

    eq score(
        'decideTrue[BT, NT, OIDT, OT, CT], D
    ) = scoreConf((OT, CT)) .
    eq score(
            'decideFalse[BT, NT, OIDT, OT, CT], D
        ) = scoreConf((OT, CT)) .
    eq score(
            'updateTrue[BT, NT, OIDT, OT, CT], D
        ) = scoreConf((OT, CT)) .
    eq score(
            'updateFalse[BT, NT, OIDT, OT, CT], D
        ) = scoreConf((OT, CT)) .

    var NETL : NeTermList .

    eq scoreConf('<_:_|_>[OT, CT, 
        '_`,_['status`:_['_`,_[NT, ST]], NETL]
    ]) 
    =  1 . 

    eq scoreConf('multicast_from_to_[NETL]) 
    = 0 .
endfm

fmod ONETHIRDRULE-SCORE3 is
    including ONETHIRDRULE-SCORE-BASE .

    vars T BT NT OIDT OT CT ST : Term .
    var D : Nat .

    eq score(
        'decideTrue[BT, NT, OIDT, OT, CT], D
    ) = scoreConf((OT, CT)) .
    eq score(
            'decideFalse[BT, NT, OIDT, OT, CT], D
        ) = scoreConf((OT, CT)) .
    eq score(
            'updateTrue[BT, NT, OIDT, OT, CT], D
        ) = scoreConf((OT, CT)) .
    eq score(
            'updateFalse[BT, NT, OIDT, OT, CT], D
        ) = scoreConf((OT, CT)) .

    var NETL : NeTermList .

    eq scoreConf('<_:_|_>[OT, CT, 
        '_`,_['status`:_['_`,_[NT, ST]], NETL]
    ]) 
    =  100 + 10 * max(2, toNumber(NT)) .

    eq scoreConf('multicast_from_to_[NETL]) 
    = -1 .
endfm

fmod ONETHIRDRULE-SCORE2' is
    including ONETHIRDRULE-SCORE-BASE .

    vars T BT NT OIDT OT CT ST : Term .
    var D : Nat .

    eq score(
            'decideTrue[BT, NT, OIDT, OT, CT], D
        ) = 0 .
    eq score(
            'decideFalse[BT, NT, OIDT, OT, CT], D
        ) = 0 .
    eq score(
            'updateTrue[BT, NT, OIDT, OT, CT], D
        ) = 0 .
    eq score(
            'updateFalse[BT, NT, OIDT, OT, CT], D
        ) = 0 .

    var NETL : NeTermList .

    eq scoreConf('<_:_|_>[OT, CT, 
        '_`,_['status`:_['_`,_[NT, ST]], NETL]
    ]) 
    = 1 . 

    eq scoreConf('multicast_from_to_[NETL]) 
    = 0 .
endfm

fmod ONETHIRDRULE-SCORE3' is
    including ONETHIRDRULE-SCORE-BASE .

    vars T BT NT OIDT OT CT ST : Term .
    var D : Nat .

    eq score(
            'decideTrue[BT, NT, OIDT, OT, CT], D
        ) = 0 .
    eq score(
            'decideFalse[BT, NT, OIDT, OT, CT], D
        ) = 0 .
    eq score(
            'updateTrue[BT, NT, OIDT, OT, CT], D
        ) = 0 .
    eq score(
            'updateFalse[BT, NT, OIDT, OT, CT], D
        ) = 0 .

    var NETL : NeTermList .

    eq scoreConf('<_:_|_>[OT, CT, 
        '_`,_['status`:_['_`,_[NT, ST]], NETL]
    ]) 
    =  100 + 10 * max(2, toNumber(NT)) .

    eq scoreConf('multicast_from_to_[NETL]) 
    = -1 .
endfm



fmod ONETHIRDRULE-VU-NARROW-SCORE1 is
    including ONETHIRDRULE-SCORE1 .

    vars T BT : Term . var D : Nat .

    eq score('ready[T], D) = score(T, D) .
    eq score('check[BT, T], D) = score(T, D) .
endfm

fmod ONETHIRDRULE-VU-NARROW-SCORE2 is
    including ONETHIRDRULE-SCORE2 .

    vars T BT : Term . var D : Nat .

    eq score('ready[T], D) = score(T, D) .
    eq score('check[BT, T], D) = score(T, D) .
endfm 

fmod ONETHIRDRULE-VU-NARROW-SCORE3 is
    including ONETHIRDRULE-SCORE3 .

    vars T BT : Term . var D : Nat .

    eq score('ready[T], D) = score(T, D) .
    eq score('check[BT, T], D) = score(T, D) .
endfm 